# Setup
title:        Pyrotexni Fireworks
tagline:      A Fireworks on your iPhone/iPad.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       D.Koci
  url:        http://dokosoft.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet